FROM alpine:latest

ADD http /usr/local/
#ADD static/ /Users/jiashiran/go/src/jumpserver-automation/static/
#ADD key/ /Users/jiashiran/go/src/jumpserver-automation/build/key/

RUN chmod +x /usr/local/http

CMD /usr/local/http